# 项目相关配置
javapress:
  # 项目信息
  name: javapress
  # 作者信息
  author: seifly
  # 项目描述
  description: java版本的wordpress内容管理平台
  # 版本信息
  version: 2.0
  # 项目网址
  url: cn.seifly
  # 联系信息
  email: goggb@qq.com
  license: MIT
  license-url: https://gitee.com/blob/master/LICENSE
  # 版权年份
  copyrightYear: 2024
  # 文件路径 示例（ Windows配置D:/uploadPath，Linux配置 /home/uploadPath）
  profile: ./uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    cn.seifly: debug
    org.springdoc: DEBUG
    org.springframework.web: DEBUG
    org.springframework.jdbc.core: debug
    org.springframework.jdbc.coreStatementCreatorUtils: debug
    org.springframework.transaction: debug
    org.springframework.transaction.interceptor: TRACE
    org.apache.ibatis: TRACE
  config: classpath:logback.xml


# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  config:
    import:
      - classpath:application-druid.yml
      - classpath:application-press.yml
      - classpath:application-wx.yml
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      #spring boot2.6.1 继承swagger报错documentationPluginsBootstrapper
      matching-strategy: ant_path_matcher
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    #active: druid
    #include: druid 该版本不行
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    # password: 123456
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.ruoyi.**.domain,cn.seifly.module.wp.dao.dataobject
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  typeAliasesPackage: com.ruoyi.**.domain,cn.seifly.module.wp.dao.dataobject
  global-config:
    # 关闭MP3.0自带的banner
    banner: true
    db-config:
      #主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
      id-type: 0
      # 默认数据库表下划线命名
      table-underline: true
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true
# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*
springdoc:
  swagger-ui:
    path: /swagger-ui.html   # 默认访问路径
    tags-sorter: alpha      # 按字母顺序排序标签
    operations-sorter: alpha
    enabled: true
  api-docs:
    path: /v3/api-docs      # JSON文档路径
    enabled: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json